# Generated by Django 3.0.3 on 2023-01-07 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0002_auto_20230107_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photocreate',
            old_name='photo',
            new_name='photos',
        ),
    ]
