# Generated by Django 3.0.3 on 2023-01-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0003_auto_20230107_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photocreate',
            name='photos',
            field=models.ImageField(upload_to='media/image/', verbose_name='Изображение'),
        ),
    ]
