# Generated by Django 3.0.3 on 2023-01-09 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0008_follow_author_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='author_follow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detail.Post'),
        ),
    ]
