# Generated by Django 3.0.3 on 2023-01-09 04:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('detail', '0009_auto_20230109_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='follow',
            field=models.ManyToManyField(related_name='create', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
