# Generated by Django 3.0.3 on 2023-01-10 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('detail', '0010_auto_20230109_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='follow',
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_follow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('follow', models.ManyToManyField(related_name='create', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
