# Generated by Django 3.0.3 on 2023-01-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0014_auto_20230111_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photos_author',
            field=models.ImageField(default=1, upload_to='media/image/', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photocreate',
            name='photos',
            field=models.ImageField(upload_to='media/image/', verbose_name='Изображение'),
        ),
    ]
