# Generated by Django 3.0.3 on 2023-01-18 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0015_auto_20230116_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='photos_author',
        ),
    ]
